Project.Application/Controllers/ApplicantsController.cs
using Project.Core;
using Project.Core.Models;
using Project.Core.Objects;
using System;
using System.Linq;
using System.Web.Mvc;
using CaptchaMvc.HtmlHelpers;
using System.Net;
using System.Collections.Specialized;
using System.Text.RegularExpressions;
using System.Text;
namespace Project.Application.Controllers
{
    public class ApplicantsController : Controller
    {
        private CompanyDbContext db = new CompanyDbContext();
        IApplicantResponsibility context = new ApplicantResponsibility();
        public bool VerifyEmail(string emailVerify)
        {
            using (WebClient webclient = new WebClient())
            {
                string url = "http://verify-email.org/";
                NameValueCollection formData = new NameValueCollection();
                formData["check"] = emailVerify;
                byte[] responseBytes = webclient.UploadValues(url, "POST", formData);
                string response = Encoding.ASCII.GetString(responseBytes);
                if (response.Contains("Result: Ok"))
                {
                    return true;
                }
                return false;
            }
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }
        public ActionResult Create(int? id)
        {
            if (id.HasValue)
            {
                Vacancy vacancy = db.Vacancies.SingleOrDefault(p => p.Id == id.Value);
                if (vacancy != null)
                {
                    ViewBag.vacancyId = id;
                    return View();
                }
            }
            return RedirectToAction("Index", "Vacancies");

        }
        [HttpPost]
        public ActionResult Create(FormCollection f)
        {
            string email = f["Email"];
            string phone = f["Phone"];
            if (!this.IsCaptchaValid("Validate your captcha"))
            {
                ViewBag.ErrorMessage = "Invalid Captcha";
                ViewBag.vacancyId = Int32.Parse(f["vacancyId"]);
                return View();
            }
            bool CheckVerifyEmail = VerifyEmail(email);
            if (!CheckVerifyEmail)
            {
                TempData["StatusMessage"] = "Invalid Email";
                ViewBag.vacancyId = Int32.Parse(f["vacancyId"]);
                return View();
            }
            TempData["StatusMessage"] = "You have applied for this job";
            Applicant CheckApplicant = context.GetApplicant(email, phone);
            if (CheckApplicant == null)
            {
                Applicant applicant = new Applicant();
                applicant.Name = f["Name"];
                applicant.Phone = f["Phone"];
                applicant.Status = true;
                applicant.Experience = f["Experience"];
                applicant.BirthDay = Convert.ToDateTime(f["BirthDay"]);
                applicant.Address = f["Address"];
                applicant.Email = f["Email"];
                applicant.AcademicLevel = f["AcademicLevel"];
                applicant.CreateAt = DateTime.Now;
                CheckApplicant = context.AddApplication(applicant);

            }
            if (CheckApplicant.Status == false)
            {
                TempData["messErr"] = "You applied to company.";
                ViewBag.vacancyId = Int32.Parse(f["vacancyId"]);
                return View();
            }
            bool NotExistApplicant = true;
            foreach (var item in context.GetVaCancyApplicantsForVacancy(Int32.Parse(f["vacancyId"])))
            {
                if (item.ApplicantId == CheckApplicant.Id)
                {
                    NotExistApplicant = false;
                }
            }
            if (!NotExistApplicant)
            {
                TempData["messErr"] = "You applied to this Job.";
                ViewBag.vacancyId = Int32.Parse(f["vacancyId"]);
                return View();
            }
            VacancyApplicant vacancyApplicant = new VacancyApplicant();
            vacancyApplicant.ApplicantId = CheckApplicant.Id;
            vacancyApplicant.VacancyId = Int32.Parse(f["vacancyId"]);
            vacancyApplicant.InterviewTime = Convert.ToDateTime(f["InterviewTime"]);
            vacancyApplicant.Status = 0;
            vacancyApplicant.CreateAt = DateTime.Now;
            vacancyApplicant.InterviewId = 1;
            context.AddVacancyApplicant(vacancyApplicant);
            return RedirectToAction("Details", "Vacancies", new { id = Int32.Parse(f["vacancyId"]) });
        }

    }
}

Project.Application/Views/Applicants/Create.cshtml
@using CaptchaMvc.HtmlHelpers;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Client.cshtml";
    int vacancyId = ViewBag.vacancyId;
}
@{
    ViewBag.Title = "Job_list";
}


<!-- breadcrumbs -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-center bg-theme">
        <li class="breadcrumb-item">
            <a href="index.html" class="text-white">Home</a>
        </li>
        <li class="breadcrumb-item active text-white font-weight-bold" aria-current="page">Applicant</li>
    </ol>
</nav>
<!-- //breadcrumbs -->
<!-- jobs -->
<section class="employ-sec">
    <div class="container">
        <div class="title-sec-w3layouts_pvt text-center pb-4">
            <span class="title-wthree">a world full of possibilities</span>
            <h4 class="w3layouts_pvt-head">allowing you to expand quickly.</h4>
        </div>
        <h1 class="w3layouts_pvt-head" style="color:red">@TempData["messErr"]</h1>
        @using (Html.BeginForm("Create", "Applicants", FormMethod.Post, new { id = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Applicant</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <input name="vacancyId" value="@vacancyId" style="display:none" />
                <div class="form-group">
                    <label class="control-label col-md-2">Name</label>
                    <div class="col-md-10">
                        <input name="Name" class="form-control" type="text" onkeyup="checkName()" id="name" required />
                        <span id="checkname" style="color:red"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">BirthDay</label>
                    <div class="col-md-10">
                        <input class="form-control" name="BirthDay" onchange="checkBirthday()" id="birthday" type="date" required />
                        <span id="checkBirthday" style="color:red"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Address</label>
                    <div class="col-md-10">
                        <input name="Address" class="form-control" onkeyup="checkAddress()" id="address" type="text" required />
                        <span id="checkaddress" style="color:red"></span>

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Email</label>
                    <div class="col-md-10">
                        <input name="Email" class="form-control" type="email" id="email" onkeyup="checkEmail()" required />
                        <span id="checkemail" style="color:red"></span>

                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Phone</label>
                    <div class="col-md-10">
                        <input name="Phone" class="form-control" id="phone" onkeyup="checkPhone()" type="text" required />
                        <span id="checkphone" style="color:red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Experience</label>
                    <div class="col-md-10">
                        <input name="Experience" class="form-control" id="experience" onkeyup="checkExperience()" type="text" required />
                        <span id="checkexprience" style="color:red"></span>

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Academic Level</label>
                    <div class="col-md-10">
                        <input name="AcademicLevel" class="form-control" id="academiclevel" onkeyup="academicLevel()" type="text" required />
                        <span id="checkacademic" style="color:red"></span>

                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Interview Time</label>
                    <div class="col-md-10">
                        <input name="InterviewTime" class="form-control" id="interviewtime" onchange="checkInterviewTime()" type="date" required />
                        <span id="checktime" style="color:red"></span>
                    </div>

                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.MathCaptcha()
                        <span style="color:red">@ViewBag.ErrorMessage</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button onclick="CheckSubmit()" class="btn btn-dark" required="required">Create</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>
<!-- //jobs -->
<!-- Footer -->


<script>
    var CheckInterviewTime = false;
    function checkInterviewTime() {
        var a = $("#interviewtime").val();
        var interviewtime = new Date(a);

        var timeNow = new Date();

        if (interviewtime <= timeNow) {
            document.getElementById("checktime").innerHTML = "*Your interview date must be greater than the current date.";
            CheckInterviewTime = false;

        } else {
            document.getElementById("checktime").innerHTML = "";
            CheckInterviewTime = true;
        }
    }
    var CheckBirthday = false;

    function checkBirthday() {
        var b = $("#birthday").val();
        var birthday = new Date(b);

        var timeNow = new Date();

        if (birthday >= timeNow) {
            document.getElementById("checkBirthday").innerHTML = "*Your birthday must be less than the current date.";
            CheckBirthday = false;

        }
        else {
            document.getElementById("checkBirthday").innerHTML = "";
            CheckBirthday = true;
        }
    }
    var CheckBirthday = false;
    function checkPhone() {
        var phone = $("#phone").val();
        var vnf_regex = /^[+]*[(]{0,1}[0-9]{1,3}[)]{0,1}[-\s\./0-9]*$/g;

        if (phone !== "") {
            if (vnf_regex.test(phone) == false) {
                document.getElementById("checkphone").innerHTML = "*Your phone number is not valid.";
                CheckBirthday = false;

            } else {
                document.getElementById("checkphone").innerHTML = "";
                CheckBirthday = true;
            }
        }
        else {
            document.getElementById("checkphone").innerHTML = "*You didn't enter a phone number."
            CheckBirthday = false;

        }
    }
    var CheckEmail = false;

    function checkEmail() {
        var email = $("#email").val();
        var vnf_regex = /^(([^<>()[\]\\.,;:\s@@\"]+(\.[^<>()[\]\\.,;:\s@@\"]+)*)|(\".+\"))@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

        if (email !== "") {
            if (vnf_regex.test(email) == false) {
                document.getElementById("checkemail").innerHTML = "*Your email is not valid.";
                CheckEmail = false;

            } else {
                document.getElementById("checkemail").innerHTML = "";
                CheckEmail = true;
            }
        }
        else {
            document.getElementById("checkemail").innerHTML = "*Your didn't enter a email.";
            CheckEmail = false;

        }
    }
    var CheckAddress = false;

    function checkAddress() {
        var address = $("#address").val();
        var vnf_regex = /^[a-zA-Z0-9-\s\,\''\-]*$/;

        if (address !== "") {
            if (vnf_regex.test(address) == false) {
                document.getElementById("checkaddress").innerHTML = "*The address must not contain special characters";
                CheckAddress = false;

            }
            else {
                document.getElementById("checkaddress").innerHTML = "";
                CheckAddress = true;
            }
        }
        else {
            document.getElementById("checkaddress").innerHTML = "*Your didn't enter a address.";
            CheckAddress = false;

        }
    }
    var CheckName = false;

    function checkName() {
        var name = $("#name").val();
        var vnf_regex = /^[a-zA-Z-\s\,\''\-]*$/;

        if (name !== "") {
            if (vnf_regex.test(name) == false) {
                document.getElementById("checkname").innerHTML = "*The address must not contain special characters";
                CheckName = false;
            }
            else {
                document.getElementById("checkname").innerHTML = "";
                CheckName = true;
            }
        }
        else {
            document.getElementById("checkname").innerHTML = "*Your didn't enter a name.";
            CheckName = false;

        }
    }
    var CheckExperience = false;
    function checkExperience() {
        var experience = $("#experience").val();
        var vnf_regex = /^[a-zA-Z0-9-\s\,\''\-]*$/;

        if (experience !== "") {
            if (vnf_regex.test(experience) == false) {
                document.getElementById("checkexprience").innerHTML = "*The address must not contain special characters";
                CheckExperience = false;
            }
            else {
                document.getElementById("checkexprience").innerHTML = "";
                CheckExperience = true;
            }
        }
        else {
            document.getElementById("checkexprience").innerHTML = "*Your didn't enter a exprience.";
            CheckExperience = false;
        }
    }
    var CheckacademicLevel = false;
    function academicLevel() {
        var academiclevel = $("#academiclevel").val();
        var vnf_regex = /^[a-zA-Z0-9-\s\,\''\-]*$/;

        if (academiclevel !== "") {
            if (vnf_regex.test(academiclevel) == false) {
                document.getElementById("checkacademic").innerHTML = "*The address must not contain special characters";
                CheckacademicLevel = false;

            }
            else {
                document.getElementById("checkacademic").innerHTML = "";
                CheckacademicLevel = true;
            }
        }
        else {
            document.getElementById("checkacademic").innerHTML = "*Your didn't enter a academic.";
            CheckacademicLevel = false;
        }
    }
    var checkValid = false;

    function CheckSubmit() {
        if (CheckName && CheckPhone && CheckExperience && CheckacademicLevel && CheckAddress && CheckBirthday && CheckEmail && CheckInterviewTime) {
            checkValid = true;
        } else {
            checkValid = false;
        }
        if (checkValid) {
            $("#form").submit();
        } else {
            alert("Error.");
        }
    }
</script>