Project.Application/Controllers/ApplicantManagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Project.Core;
using Project.Core.Objects;

namespace Project.Application.Controllers
{
    public class ApplicantManagesController : Controller
    {
        private CompanyDbContext db = new CompanyDbContext();

        // GET: ApplicantManages
        public ActionResult Index()
        {
            return View(db.Applicants.ToList());
        }
     
        // GET: ApplicantManages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }

        // GET: ApplicantManages/Create


        // GET: ApplicantManages/Delete/5

    }
}

Project.Application/Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Core.Objects;
using Project.Core.Models;
using Project.Core;
using PagedList;

namespace Project.Application.Controllers
{
    public class InterviewsController : Controller
    {
        // GET: Interviews
        IInterViewResponsibility resp = new InterviewResponsibility();
        private CompanyDbContext context = new CompanyDbContext();
        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;
            if (page < 0 || page % 1 != 0)
            {
                return View("Error");
            }
            List<Interview> Interviews = resp.GetInterviews();
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(Interviews.Where(p => p.Id != 1).OrderBy(x => x.Id).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(context.Users.Where(p=>p.TypeUserId==2),"Id","Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create( Interview interview)
        {
            bool IsCheck = true;
            if (interview != null)
            {
                foreach (var item in resp.GetInterviews())
                {
                    if (item.UserId==interview.UserId)
                    {
                        IsCheck = false;
                    }
                }
                if (IsCheck)
                {
                    interview = resp.CreateInterView(interview);
                    return RedirectToAction("Index");
                }
            }

            ViewBag.UserId = new SelectList(context.Users.Where(p => p.TypeUserId == 2), "Id", "Name");
            return View();
        }
    }
}

Project.Application/Controllers/VacancyApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Core.Models;
using Project.Core.Objects;
using Project.Core;
using PagedList;

namespace Project.Application.Controllers
{
    public class VacancyApplicantController : Controller
    {
        // GET: VacancyApplicant
        IVacancyResponsibility resp = new VacancyResponsibility();
        private CompanyDbContext context = new CompanyDbContext();
        public ActionResult Index()
        {
          
                List<VacancyApplicant> VacancyApplicants = resp.GetVacancyApplicants().Where(p => p.Status == 0 && p.InterviewId != 1).ToList();
                
                return View(VacancyApplicants.OrderBy(x => x.Id).ToList());
  
        }
        public ActionResult List()
        {


                List<VacancyApplicant> VacancyApplicants = resp.GetVacancyApplicants().ToList();

                return View(VacancyApplicants.OrderBy(x => x.Id).ToList());

            
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }
        public ActionResult InterviewCensorship()
        {
                List<VacancyApplicant> VacancyApplicants = resp.GetVacancyApplicants();

                Interview interview = new Interview();

                return View(VacancyApplicants.Where(p => p.Status == 0 && p.InterviewId == 1).OrderBy(x => x.Id).ToList());
   
        }
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                VacancyApplicant vacancyApplicant = resp.GetVacancyApplicant(id.Value);
                if (vacancyApplicant!=null)
                {
                    ViewBag.Interviews = context.Interviews.ToList();
                    return View(vacancyApplicant);
                }
            }
            return RedirectToAction("InterviewCensorship");
        }
        [HttpPost]
        public ActionResult Edit(VacancyApplicant data)
        {
            List<VacancyApplicant> VacancyApplicants ;
            
            if (data != null)
            {
                bool check = true;
                VacancyApplicants = resp.GetVacancyApplicants().Where(p=>p.InterviewId==data.InterviewId).ToList();
                foreach (var item in VacancyApplicants)
                {
                    if (item.InterviewTime==data.InterviewTime && item.Id != data.Id)
                    {
                        check = false;
                    }
                }
                VacancyApplicants = resp.GetVacancyApplicants().Where(p => p.ApplicantId == data.ApplicantId).ToList();
                foreach (var item in VacancyApplicants)
                {
                    if (item.InterviewTime == data.InterviewTime && item.Id != data.Id)
                    {
                        check = false;
                    }
                }
                if (check)
                {
                    VacancyApplicant vacancyApplicant = resp.UpdateVacancyApplicant(data);
                    if (vacancyApplicant != null)
                    {
                        return RedirectToAction("Details", new { id = vacancyApplicant.Id });
                    }
                }
            }
            ViewBag.Interviews = context.Interviews.ToList();
            VacancyApplicant VacancyApplicant = resp.GetVacancyApplicant(data.Id);
            VacancyApplicant.InterviewTime = data.InterviewTime;
            return View(VacancyApplicant);
        }
        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                VacancyApplicant vacancyApplicant = resp.GetVacancyApplicant(id.Value);
                if (vacancyApplicant != null)
                {
                    return View(vacancyApplicant);
                }
            }
            return RedirectToAction("InterviewCensorship");
        }
        public ActionResult Details01(int? id)
        {
            if (id.HasValue)
            {
                VacancyApplicant vacancyApplicant = resp.GetVacancyApplicant(id.Value);
                if (vacancyApplicant != null)
                {
                    return View(vacancyApplicant);
                }
            }
            return RedirectToAction("InterviewCensorship");
        }
        public ActionResult Interview(int? page)
        {
            if (page > 0 || page % 1 != 0)
            {
                if (Session["Login"] != null)
                {
                    User user = Session["Login"] as User;
                    List<Interview> Interviews = user.Interviews.ToList();
                    if (page == null) page = 1;
                    int pageSize = 1;
                    int pageNumber = (page ?? 1);
                    return View(Interviews.Where(p => p.Id != 1).OrderBy(x => x.Id).ToPagedList(pageNumber, pageSize));
                }
                return RedirectToAction("Index", "Vacancies");
            }
            return View("Error");
            

        }

    }
}

Project.Application/Views/VacancyApplicant/Details.cshtml
@model Project.Core.Objects.VacancyApplicant

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Interview Censorship</h2>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("InterviewCensorship","VacancyApplicant")" class="breadcrumb-link">Interview Censorship</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Details</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader -->
<!-- ============================================================== -->

<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Applicant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Applicant.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interview.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vacancy.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vacancy.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterviewTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", "Interviews")
</p>

Project.Application/Views/VacancyApplicant/Details01.cshtml
@model Project.Core.Objects.VacancyApplicant

@{
    ViewBag.Title = "Details01";
    Layout = "~/Views/Shared/_Client.cshtml";
}


<h2>Details</h2>

<div>
    <h4>VacancyApplicant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Applicant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Applicant.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interview.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vacancy.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vacancy.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterviewTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Interview", "VacancyApplicant")
</p>

Project.Application/Views/VacancyApplicant/Edit.cshtml
@using Project.Core.Objects;
@model VacancyApplicant

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Interview> Interviews = ViewBag.Interviews as List<Interview>;
}
<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Interview Censorship</h2>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("InterviewCensorship","VacancyApplicant")" class="breadcrumb-link">Interview Censorship</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader -->
<!-- ============================================================== -->

@using (Html.BeginForm("Edit", "VacancyApplicant", FormMethod.Post, new { id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Interview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input name="Id" value="@Model.Id" hidden />
        <div class="form-group">
            <label class="control-label col-md-2">Name Applicant</label>
            <div class="col-md-10">
                <span> <a href="@Url.Action("Detail","ApplicantManages",new {id= Model.ApplicantId})"></a>@Model.Applicant.Name</span>
                <input name="ApplicantId" value="@Model.ApplicantId" hidden />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Vacancy</label>
            <div class="col-md-10">
                <span>@Model.Vacancy.Name</span>
                <input name="VacancyId" value="@Model.VacancyId" hidden />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="Status" class="form-control">
                    <option @((Model.Status == 0) ? "selected" : "") value="0">Doing</option>
                    <option @((Model.Status == 1) ? "selected" : "" ) value="1">False</option>
                    <option @((Model.Status == 2) ? "selected" : "") value="2">Pass</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="datetime" id="InterviewTime" value="@Model.InterviewTime" class="form-control" name="InterviewTime" onkeyup="Datetime()" />
            </div>
            <span id="checkInterviewTime" style="color:red"></span>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateAt, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.CreateAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewId, "InterviewId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="InterviewId">
                    @foreach (var item in Interviews)
                    {
                        <option value="@item.Id" @(item.Id == Model.InterviewId ? "selected" : "")>@item.User.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" onclick="CheckSubmit()" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Interviews")
</div>
<script>
    var checkValid = true;
    function Datetime() {
        var academiclevel = $("#InterviewTime").val();
        var vnf_regex = /((1[0-2]|0?[1-9]):([0-5][0-9]):([0-5][0-9]) ?([AaPp][Mm]))/;
        if (vnf_regex.test(academiclevel) == false) {
            document.getElementById("checkInterviewTime").innerHTML = "*The InterviewTime is not valid !";
            checkValid = false;
        }
        else {
            document.getElementById("checkInterviewTime").innerHTML = "";
            checkValid = true;
        }

    }
    function CheckSubmit() {
        if (checkValid) {
            $("#form").submit();
        } else {
            alert("Error.");
        }
    }
</script>

Project.Application/Views/VacancyApplicant/Index.cshtml
@model ICollection<Project.Core.Objects.VacancyApplicant>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Vacancy Applicant</h2>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","VacancyApplicant")" class="breadcrumb-link">Vacancy Applicant</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Index</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader -->
<!-- ============================================================== -->
<hr />
<a href="@Url.Action("List")">All Vacancy Aplicants</a>

<!-- data table  trong VacancyApplicant/List.cshtml-->
<!-- ============================================================== -->
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="mb-0">Vacancy Applicant</h3>

        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="example" class="table table-striped table-bordered second" style="width:100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Interview</th>
                            <th>Vacancy</th>
                            <th>Status</th>
                            <th>Interview Time</th>
                            <th>Create At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Applicant.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Interview.User.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Vacancy.Name)
                                </td>
                                <td>
                                    @((item.Status == 0)?"Doing":(item.Status==1)?"False":"Pass")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.InterviewTime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreateAt)
                                </td>
                                <td>
                                    @Html.ActionLink("Censorship", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                                </td>
                            </tr>
}
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end data table  -->

Project.Application/Views/VacancyApplicant/Interview.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Project.Core.Objects.Interview>


@{
    ViewBag.Title = "Interview";
    Layout = "~/Views/Shared/_Client.cshtml";
}

<h2 class="text-center">Interview Management</h2>
@using (Html.BeginForm())
{
    <input type="search" name="search" required />
    <input type="submit" value="Search by name" />
}

<table class="table">
    <tr>
        <th>
            Interviewer
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.User.Name
            </td>
            <td>
                <table class="table">
                    <tr>
                        <th>
                            Applicant
                        </th>
                        <th>
                            Vacancy
                        </th>
                        <th>
                            Interview time
                        </th>
                        <th>

                        </th>

                    </tr>
                    @foreach (var interview in item.VacancyApplicants.Where(p => p.Status == 0))
                    {
                        <tr>
                            <td>
                                @interview.ApplicantId - @interview.Applicant.Name
                            </td>
                            <td>
                                @interview.VacancyId - @interview.Vacancy.Name
                            </td>
                            <td>
                                @interview.InterviewTime
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details01", "VacancyApplicant", new { id = interview.Id }, null)
                            </td>
                        </tr>
                    }
                </table>
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page }))

Project.Application/Views/VacancyApplicant/InterviewCensorship.cshtml
@model ICollection<Project.Core.Objects.VacancyApplicant>


@{
    ViewBag.Title = "InterviewCensorship";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Interview Censorship</h2>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("InterviewCensorship","VacancyApplicant")" class="breadcrumb-link">Interview Censorship</a></li>
                        <li class="breadcrumb-item active" aria-current="page">List</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader -->
<!-- ============================================================== -->


<!-- data table  trong VacancyApplicant/InterviewCensorship.cshtml-->
<!-- ============================================================== -->
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="mb-0">Interview Censorship</h3>

        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="example" class="table table-striped table-bordered second" style="width:100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Interview</th>
                            <th>Vacancy</th>
                            <th>Status</th>
                            <th>Interview Time</th>
                            <th>Create At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Applicant.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Interview.User.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vacancy.Name)
                </td>
                <td>
                    @((item.Status == 0)?"In process":(item.Status==1)?"False":"Pass")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterviewTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateAt)
                </td>
                <td>
                    @Html.ActionLink("Censorship", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end data table  -->

Project.Application/Views/VacancyApplicant/List.cshtml
@model ICollection<Project.Core.Objects.VacancyApplicant>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ============================================================== -->
<!-- pageheader -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 class="pageheader-title">Vacancy Applicant</h2>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","VacancyApplicant")" class="breadcrumb-link">Vacancy Applicant</a></li>
                        <li class="breadcrumb-item active" aria-current="page">List</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader -->
<!-- ============================================================== -->

<!-- data table  trong VacancyApplicant/List.cshtml-->
<!-- ============================================================== -->
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="mb-0">Vacancy Applicant</h3>

        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="example" class="table table-striped table-bordered second" style="width:100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Interview</th>
                            <th>Vacancy</th>
                            <th>Status</th>
                            <th>Interview Time</th>
                            <th>Create At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Applicant.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Interview.User.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vacancy.Name)
                </td>
                <td>
                    @((item.Status == 0)?"Doing":(item.Status==1)?"False":"Pass")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterviewTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateAt)
                </td>
                <td>
                    @Html.ActionLink("Censorship", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>}
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end data table  -->