Project.Application/Controllers/ApplicantManagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Project.Core;
using Project.Core.Objects;

namespace Project.Application.Controllers
{
    public class ApplicantManagesController : Controller
    {
        private CompanyDbContext db = new CompanyDbContext();

        // GET: ApplicantManages
        public ActionResult Index()
        {
            return View(db.Applicants.ToList());
        }
     
        // GET: ApplicantManages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }

        // GET: ApplicantManages/Create


        // GET: ApplicantManages/Delete/5

    }
}

Project.Application/Controllers/DefaultController.cs
using Project.Core;
using Project.Core.Models;
using Project.Core.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
namespace Project.Application.Controllers
{
    public class DefaultController : Controller
    {
        private CompanyDbContext db = new CompanyDbContext();
        IUserAccount resp = new UserAccResponsibility();
        // GET: Default
        public ActionResult Index()
        {
            ViewBag.TotalApplicant = db.Applicants.Count();
            ViewBag.TotalVacancy = db.Vacancies.Count();
            ViewBag.VacancyApplicant = db.VacancyApplicants.Count();
            List<Applicant> Applicants = db.Applicants.Where(p => p.Status == false).ToList();
            if (Applicants!=null)
            {
                ViewBag.ApplicantSuccess = Applicants.Count();
            }
            else
            {
                ViewBag.ApplicantSuccess = 0;
            }
            return View();
        }
        public PartialViewResult Menu()
        {
            return PartialView();
        }

        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }
        public ActionResult Profile(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Logout", "Login");
            }
            User user = resp.GetUser(id.Value);
            return View(user);
        }
        public ActionResult Edit(int id)
        {

            User user = resp.GetUser(id);
            return View(user);
        }
        [HttpPost]
        public ActionResult Save(FormCollection f)
        {
            int id = Int32.Parse(f["Id"]);
            User user = resp.GetUser(id);
            if (!String.IsNullOrEmpty(f["OldPass"]))
            {
                string OldPass = f["OldPass"];
                if (user.Password != OldPass)
                {
                    RedirectToAction("Logout", "Login");
                }
            }
            if (!String.IsNullOrEmpty(f["NewPass"]))
            {
                string NewPass = f["NewPass"];
                user.Password = NewPass;
            }
            user.Email = f["Email"];
            user.Avatar = f["Avatar"];
            resp.UpdateUser(user);
            return RedirectToAction("Profile", new { id = id });
        }

    }
}

Project.Application/Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Core.Objects;
using Project.Core.Models;
using Project.Core;
using PagedList;

namespace Project.Application.Controllers
{
    public class InterviewsController : Controller
    {
        // GET: Interviews
        IInterViewResponsibility resp = new InterviewResponsibility();
        private CompanyDbContext context = new CompanyDbContext();
        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;
            if (page < 0 || page % 1 != 0)
            {
                return View("Error");
            }
            List<Interview> Interviews = resp.GetInterviews();
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(Interviews.Where(p => p.Id != 1).OrderBy(x => x.Id).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(context.Users.Where(p=>p.TypeUserId==2),"Id","Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create( Interview interview)
        {
            bool IsCheck = true;
            if (interview != null)
            {
                foreach (var item in resp.GetInterviews())
                {
                    if (item.UserId==interview.UserId)
                    {
                        IsCheck = false;
                    }
                }
                if (IsCheck)
                {
                    interview = resp.CreateInterView(interview);
                    return RedirectToAction("Index");
                }
            }

            ViewBag.UserId = new SelectList(context.Users.Where(p => p.TypeUserId == 2), "Id", "Name");
            return View();
        }
    }
}

Project.Application/Controllers/VacanciesController.cs
using PagedList;
using Project.Core;
using Project.Core.Models;
using Project.Core.Objects;
using System;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Project.Application.Controllers
{
    public class VacanciesController : Controller
    {
        private CompanyDbContext db = new CompanyDbContext();
        IVacancyResponsibility resp = new VacancyResponsibility();
        // GET: Vacancies
        private User GetUser()
        {
            User user = Session["Login"] as User;
            return user;
        }
        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;
            var vacancies = db.Vacancies.Where(p => p.Status == 0).OrderBy(x => x.Id);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(vacancies.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult Index(FormCollection f, int? page)
        {
            string search = f["search"];
            string option = f["option"];
            if (page == null) page = 1;
            var vacancies = db.Vacancies.Where(p => p.Status == 0).OrderBy(x => x.Id);
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            if (option == "Name")
            {
                vacancies = db.Vacancies.Where(p => p.Status == 0 && p.Name.Contains(search)).OrderBy(x => x.Id);
                return View(vacancies.ToPagedList(pageNumber, pageSize));
            }
            else if (option == "Language")
            {
                vacancies = db.Vacancies.Where(p => p.Status == 0 && p.Language.Contains(search)).OrderBy(x => x.Id);
                return View(vacancies.ToPagedList(pageNumber, pageSize));
            }
            else if (option == "Salary")
            {
                vacancies = db.Vacancies.Where(p => p.Status == 0 && p.Salary.Contains(search)).OrderBy(x => x.Id);
                return View(vacancies.ToPagedList(pageNumber, pageSize));
            }
            else if (option == "Location")
            {
                vacancies = db.Vacancies.Where(p => p.Status == 0 && p.Location.Contains(search)).OrderBy(x => x.Id);
                return View(vacancies.ToPagedList(pageNumber, pageSize));
            }
            else if (option == "Experience")
            {
                vacancies = db.Vacancies.Where(p => p.Status == 0 && p.Experience.Contains(search)).OrderBy(x => x.Id);
                return View(vacancies.ToPagedList(pageNumber, pageSize));
            }
            return View(vacancies.ToPagedList(pageNumber, pageSize));
        }

        // GET: Vacancies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy vacancy = db.Vacancies.Find(id);
            if (vacancy == null)
            {
                return HttpNotFound();
            }
            return View(vacancy);
        }
        public ActionResult Error()
        {
            return RedirectToAction("Index", "Login");
        }
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Vacancy vacancy)
        {
            if (ModelState.IsValid)
            {
                vacancy.CreateBy = GetUser().Id;
                vacancy.Posted = DateTime.Now;
                vacancy.Status = 0;
                resp.CreateVacancy(vacancy);
                return RedirectToAction("List");
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "Name");
            return View();

        }
        public ActionResult List(FormCollection f, int? page)
        {
            if ((page > 0 && page % 1 == 0) || page == null)
            {
                string search = f["search"];
                ViewBag.Title = "List";
                var vacancies = db.Vacancies.OrderBy(x => x.Id);
                if (page == null) page = 1;
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                if (search != null)
                {
                    return View(vacancies.Where(p => p.Name.Contains(search)).ToPagedList(pageNumber, pageSize));
                }
                return View(vacancies.ToPagedList(pageNumber, pageSize));
            }
            return View("Error");
        }
        public ActionResult StatusDoing(FormCollection f, int? page)
        {
            if ((page > 0 && page % 1 == 0) || page == null)
            {
                string search = f["search"];
                ViewBag.Title = "StatusDoing";
                var vacancies = db.Vacancies.Where(p => p.Status == 0).OrderBy(x => x.Id);
                if (page == null) page = 1;
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                if (search != null)
                {
                    return View("List", vacancies.Where(p => p.Name.Contains(search)).ToPagedList(pageNumber, pageSize));
                }
                return View("List", vacancies.ToPagedList(pageNumber, pageSize));
            }
            return View("Error");
        }
        public ActionResult StatusPause(FormCollection f, int? page)
        {
            if ((page > 0 && page % 1 == 0) || page == null)
            {
                string search = f["search"];
                ViewBag.Title = "StatusPause";
                var vacancies = db.Vacancies.Where(p => p.Status == 1).OrderBy(x => x.Id);
                if (page == null) page = 1;
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                if (search != null)
                {
                    return View("List", vacancies.Where(p => p.Name.Contains(search)).ToPagedList(pageNumber, pageSize));
                }
                return View("List", vacancies.ToPagedList(pageNumber, pageSize));
            }
            return View("Error");

        }
        public ActionResult StatusStop(FormCollection f, int? page)
        {
            if ((page > 0 && page % 1 == 0) || page == null)
            {
                string search = f["search"];
                ViewBag.Title = "StatusStop";
                var vacancies = db.Vacancies.Where(p => p.Status == 2).OrderBy(x => x.Id);
                if (page == null) page = 1;
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                if (search != null)
                {
                    return View("List", vacancies.Where(p => p.Name.Contains(search)).ToPagedList(pageNumber, pageSize));
                }
                return View("List", vacancies.ToPagedList(pageNumber, pageSize));
            }
            return View("Error");

        }
        public ActionResult Owner(FormCollection f, int? page)
        {
            if ((page > 0 && page % 1 == 0) || page == null)
            {
                User user = Session["Login"] as User;
                if (page == null) page = 1;
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                if (user != null)
                {
                    string search = f["search"];
                    ViewBag.Title = "Owner";
                    var vacancies = db.Vacancies.Where(p => p.CreateBy == user.Id);
                    if (vacancies.Count() > 0)
                    {
                        vacancies = vacancies.OrderBy(x => x.Id);

                        if (search != null)
                        {
                            return View("List", vacancies.Where(p => p.Name.Contains(search)).ToPagedList(pageNumber, pageSize));
                        }
                    }
                    return View("List", vacancies.ToPagedList(pageNumber, pageSize));
                }
                return RedirectToAction("List");
            }
            return View("Error");

        }
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                Vacancy vacancy = resp.GetVacancy(id.Value);

                if (vacancy == null || vacancy.Status == 2)
                {
                    return RedirectToAction("List");
                }

                User Creater = db.Users.Single(p => p.Id == vacancy.CreateBy);
                ViewBag.Creater = Creater.Name;
                return View(vacancy);
            }
            return RedirectToAction("List");
        }
        [HttpPost]
        public ActionResult Edit(Vacancy vacancy)
        {
            if (vacancy.CreateBy == GetUser().Id)
            {
                resp.UpdateVacancy(vacancy);
                return RedirectToAction("DetailsVacancy", new { id = vacancy.Id });
            }
            return RedirectToAction("List");
        }
        public ActionResult DetailsVacancy(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy vacancy = db.Vacancies.Find(id);

            if (vacancy == null)
            {
                return RedirectToAction("List");
            }
            User creater = db.Users.Single(p => p.Id == vacancy.CreateBy);
            ViewBag.CreateBy = creater.Name;
            return View(vacancy);
        }
    }
}

Project.Application/Views/Default/Edit.cshtml
@model Project.Core.Objects.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Save","Default",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-10">
            <input name="Email" value="@Model.Email" class="form-control" id="Email" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Avatar</label>
        <div class="col-md-10">
            <input name="Avatar" value="@Model.Avatar" class="form-control" onchange="changeAvatar()" id="avatar" placeholder="Image link" />
            <img src="@Model.Avatar" width="60px" height="80px" id="avt" />
            @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Old Password</label>
        <div class="col-md-10">
            <input name="OldPass" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">New Password</label>
        <div class="col-md-10">
            <input name="NewPass"  class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Profile", "Profile")
</div>
<script>
    function changeAvatar() {
        src = $("#avatar").val();
        $("#avt").attr("src", src);
    }
</script>

Project.Application/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Dashboard</h1>
            <ol class="breadcrumb mb-4">
            </ol>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body text-center" style="font-size:20px; font-weight:bold">Total Applicants</div>
                        <div class="card-footer" style="height:200px">
                            <div class="card-text text-center pt-3" style="color:black;height:160px;font-size:100px">@ViewBag.TotalApplicant</div>
                            <div class="" style="height:40px; float:right"><a class="text-black" href="@Url.Action("Index","ApplicantManages")">View Details</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-warning text-white mb-4">
                        <div class="card-body text-center" style="font-size:20px; font-weight:bold">Total Vacancies</div>
                        <div class="card-footer" style="height:200px">
                            <div class="card-text text-center pt-3" style="color:black;height:160px;font-size:100px">@ViewBag.TotalVacancy</div>
                            <div class="" style="height:40px; float:right"><a class="text-black" href="@Url.Action("Index","VacancyApplicant")">View Details</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-danger text-white mb-4">
                        <div class="card-body text-center" style="font-size:20px; font-weight:bold">Total Interviews</div>
                        <div class="card-footer" style="height:200px">
                            <div class="card-text text-center pt-3" style="color:black;height:160px;font-size:100px">@ViewBag.VacancyApplicant</div>
                            <div class="" style="height:40px; float:right"><a class="text-black" href="@Url.Action("Index","Interviews")">View Details</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-success text-white mb-4">
                        <div class="card-body text-center" style="font-size:20px; font-weight:bold">Applicant Success</div>
                        <div class="card-footer" style="height:200px">
                            <div class="card-text text-center pt-3" style="color:black;height:160px;font-size:100px">@ViewBag.ApplicantSuccess</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Interview
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Interviewer</th>
                                    <th>Vacancy</th>
                                    <th>Total Applicant</th>
                                    <th>Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Tiger Nixon</td>
                                    <td>System Architect</td>
                                    <td>Edinburgh</td>
                                    <td>61</td>
                                </tr>

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
    </div>

Project.Application/Views/Default/Menu.cshtml
<div class="nav-left-sidebar sidebar-dark">
    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 100%;">
        <div class="menu-list" style="overflow: hidden; width: auto; height: 100%;">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav flex-column">
                        <li class="nav-divider">
                            <h3 style="color:white">Menu</h3>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","ApplicantManages")"><i class="fa fa-user pb-1" aria-hidden="true" style="color:white"></i>Applicants Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Interviews")"><i class="fa fa-bell pb-1" aria-hidden="true" style="color:white"></i>Interviews Management </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","Vacancies")"><i class="fa fa-briefcase pb-1" aria-hidden="true" style="color:white"></i>Vacancies Management </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("InterviewCensorship","VacancyApplicant")"><i class="fa fa-address-card pb-1" aria-hidden="true" style="color:white"></i>Interviews Censorship</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","VacancyApplicant")"><i class="fa fa-paper-plane pb-1" aria-hidden="true" style="color:white"></i>Vacancy Applicant</a>
                        </li>

                    </ul>
                </div>
            </nav>
        </div><div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 722.8px;"></div><div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div>
    </div>
</div>

Project.Application/Views/Default/Profile.cshtml
@model Project.Core.Objects.User

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profile</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <i class="fa fa-shield" aria-hidden="true"></i> Position
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeUser.Name)
        </dd>
        <hr />
        <dt>
            <i class="fa fa-user" aria-hidden="true"></i> Full Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <hr />
        <dt>
            <i class="fa fa-birthday-cake" aria-hidden="true"></i> Birthday
        </dt>
        <dd>
            @String.Format("{0:dddd, dd MMM yyyy}", Model.Birthday)

        </dd>
        <hr />
        <dt>
            <i class="fa fa-envelope" aria-hidden="true"></i> Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<hr />
<p>
    @Html.ActionLink("Edit Profile", "Edit", new { id = Model.Id })
</p>